"""Fixed report copy: the 20 audit points, client explanations, resource directory,
glossary and disclosures. Sources: docs/council/r3_identity_audit.md §3, §6, §7;
r3_commercial_bureaus.md §0, §9; RULEBOOK §12. Edit wording here, not in code."""

POINTS = {
    1: {
        "title": "EIN / IRS Identity",
        "what": "Your EIN is your business's federal tax ID, issued by the IRS. It's the number that identifies your company on every bank, bureau and loan record.",
        "lender": "Lenders match your business by this number. If any record shows a different number, the application can stop at identity verification.",
        "pass": "One EIN matching exactly across the IRS record, the bank record and all commercial bureau files, with the IRS EIN notice on file.",
        "why": "The EIN is the primary key lenders, banks and bureaus use to match the business. A mismatch can fail KYC or TIN matching outright and fragment bureau files. This is an identity issue, not a tax matter.",
        "where": "Bank relationship officer (account profile and current W-9). Optional: IRS Business & Specialty Tax Line, 800-829-4933, for a Letter 147C; IRS Form 8822-B for address or responsible-party changes.",
    },
    2: {
        "title": "Secretary of State Registration",
        "what": "Your state registration is the filing that legally created your company with the Secretary of State, plus its current standing.",
        "lender": "A lender can only lend to a company that legally exists and is in good standing. A lapsed filing can stop a closing.",
        "pass": "Entity documented as validly formed with a complete filing chain and an active status on the live state record, with a fresh status certificate obtained near submission where the lender requires it.",
        "why": "Lenders confirm the entity exists and is in good standing before closing; a lapsed entity can't sign loan documents.",
        "where": "The formation state's Secretary of State business-entity search and certificate ordering (find the office via nass.org).",
    },
    3: {
        "title": "Registered Agent",
        "what": "Your registered agent is the person or company the state has on file to receive legal notices for your business.",
        "lender": "A missing or lapsed agent can put your company out of good standing. Lenders check it as part of basic legal review.",
        "pass": "A registered agent on file at the Secretary of State with a current designation and an in-state street address.",
        "why": "A valid agent keeps the entity in good standing and ensures legal notices are received.",
        "where": "State Secretary of State change-of-agent filing.",
    },
    4: {
        "title": "NAICS / SIC Consistency",
        "what": "NAICS and SIC codes are standard numbers that describe what industry you're in.",
        "lender": "Lenders sort and screen applications by industry. A blank or conflicting code can put you in the wrong group or on a restricted list.",
        "pass": "One truthful NAICS and one truthful SIC, identical across all commercial bureaus and consistent with the description of business used on applications.",
        "why": "Underwriting and automated screens route by industry code; many lenders keep restricted-industry lists, and a blank code can't be benchmarked.",
        "where": "census.gov/naics; OSHA SIC Manual; Experian BusinessCreditFacts.com; D&B D-U-N-S Manager; Equifax Commercial Research Request.",
    },
    5: {
        "title": "Licensing (if applicable)",
        "what": "Some industries need a state or professional license to operate. This point checks whether yours does and whether it's current.",
        "lender": "Operating without a required license is usually an automatic decline. A documented \"not required\" answer removes the question.",
        "pass": "Either a documented determination that no specialized license is required, or a current license on file matching the exact legal name and master address.",
        "why": "Operating without a required license is a hard decline; claiming one that doesn't exist is a misrepresentation.",
        "where": "SBA \"Apply for licenses and permits\"; the state licensing board for the activity; city/county business-permit office.",
    },
    6: {
        "title": "Business Phone / 411",
        "what": "This is a business phone number listed under your company name in directory assistance (411).",
        "lender": "Many lenders and card issuers check that a listed phone matches your business name and address. It's a quick sign the business is real.",
        "pass": "A dedicated business number listed in directory assistance under the exact legal name and master address, populated at every commercial bureau.",
        "why": "A listed, verifiable phone is one of the most commonly checked data points; some lenders and issuers verify it against name and address.",
        "where": "ListYourself.net (free national directory-assistance listing); your phone carrier's listing service; bureau update channels.",
    },
    7: {
        "title": "Business Domain",
        "what": "Your domain is your web address (yourbusiness.com), owned by the company.",
        "lender": "A matching domain helps prove the business is established and supports your website and email.",
        "pass": "An active domain matching the legal or filed trade name, controlled by the business.",
        "why": "A matching domain supports identity verification and underpins professional email, the website and the Google profile.",
        "where": "Your domain registrar; lookup.icann.org to check registration.",
    },
    8: {
        "title": "Professional Email",
        "what": "A professional email uses your own domain (you@yourbusiness.com) instead of a free service.",
        "lender": "Some lenders see free email on an application as a small warning sign. Bureaus also give more weight to update requests from a business address.",
        "pass": "All applications and bureau correspondence sent from a domain-matched business email address.",
        "why": "Several lenders treat free-mail addresses as a minor negative signal, and bureau updates from a domain-matched officer address carry more weight.",
        "where": "The email host for your domain.",
    },
    9: {
        "title": "Website",
        "what": "Your website describes your business, products and contact details.",
        "lender": "When your credit file is thin, underwriters look online to confirm the business is real and does what you say.",
        "pass": "A live website representing the business, showing the legal or filed trade name and the master address/phone consistently.",
        "why": "When the bureau file is thin, analysts look for a coherent web presence to corroborate the business.",
        "where": "Your website host; then submit the URL to each bureau.",
    },
    10: {
        "title": "Business Banking",
        "what": "This covers your business bank account in the company's legal name and your recent statements.",
        "lender": "Statements show lenders your real cash flow, balances and any overdrafts. Most business loans start here.",
        "pass": "Three or more months of complete statements; account titled in the exact legal name; statement address matching the master address; no NSF or overdraft activity; deposits consistent with reported revenue.",
        "why": "Statements show real cash flow; lenders compare deposits to stated revenue and check balances and overdrafts.",
        "where": "Online banking or your relationship officer.",
    },
    11: {
        "title": "Business Credit Bureaus",
        "what": "Business credit bureaus (Experian, Dun & Bradstreet, Equifax) keep credit files on companies, separate from your personal credit.",
        "lender": "Lenders pull these files to score your business. Missing, thin or wrong files limit what you can qualify for.",
        "pass": "All commercial bureau files reviewed within 90 days, identity data identical across them, and a generated score at Experian and D&B.",
        "why": "Lenders and card issuers pull business bureau files to score and identify the business; wrong identity data or no score routes the application to decline or manual review.",
        "where": "See the bureau cards in Section 10 and the Resource Directory. Fix identity before building depth.",
    },
    12: {
        "title": "Vendor / Payment Experiences",
        "what": "These are vendor and supplier accounts that report your on-time payments to the business bureaus.",
        "lender": "Business scores are built from reported payment history. Without it, even a profitable company can look brand new.",
        "pass": "Three or more active reporting trade accounts at both Experian and D&B, at least five overall, the oldest six months or more, all paid on terms, with a PAYDEX generated.",
        "why": "Business scores need reported payment experiences; a thin file can't produce a PAYDEX and reads as a new business.",
        "where": "Real vendors you already use that report to the business bureaus — opened only after the identity corrections are complete.",
    },
    13: {
        "title": "LexisNexis",
        "what": "LexisNexis is a data company many lenders use to verify identity and check public records on a business.",
        "lender": "It's often where duplicate or conflicting records show up, so lenders rely on it to confirm who they're dealing with.",
        "pass": "LexisNexis business file obtained within 90 days showing one business identity, every address explained, and public records matching the UCC review.",
        "why": "Lenders' identity and fraud screens draw on LexisNexis; conflicting identities or unexplained addresses there trigger manual review.",
        "where": "LexisNexis Risk Solutions business-file request; owner's personal disclosure at consumer.risk.lexisnexis.com.",
    },
    14: {
        "title": "Google Business Profile",
        "what": "Your Google Business Profile is the listing that shows your business on Google Search and Maps.",
        "lender": "A verified profile is independent proof of your name, address and phone, and lenders can check it in seconds.",
        "pass": "A verified profile (or a documented ineligibility determination) whose name, address or service area, and phone match the master record, website and directory listing.",
        "why": "A verified profile is low-cost independent corroboration of name, address and phone.",
        "where": "business.google.com — create or claim only after the master address is designated. Google does not accept virtual offices or mailboxes as a location.",
    },
    15: {
        "title": "Proof of Business Address",
        "what": "This is the one business address you use everywhere, plus documents that prove it (a lease or utility bill).",
        "lender": "When different records show different addresses, lenders slow down, ask for more documents, or quietly decline.",
        "pass": "One master address appearing identically at the IRS, the bank, all commercial bureaus, LexisNexis, the website, the Google profile and directory assistance, with supporting proof in the funding file.",
        "why": "Address consistency is the backbone of business identity verification; conflicting addresses trigger manual review and document requests.",
        "where": "See the Master Business Address Decision (Section 06). IRS Form 8822-B only if the IRS record must change; bureau update channels.",
    },
    16: {
        "title": "Foreign Qualification",
        "what": "If your company was formed in one state but operates in another, it usually has to register in the second state too.",
        "lender": "An unregistered company can face penalties and may be unable to enforce contracts there. Lenders check this.",
        "pass": "Registered in every state where the company transacts business, or documented confirmation that no out-of-state nexus exists.",
        "why": "An unregistered company can face penalties and may be barred from enforcing contracts in that state; lenders check this in diligence.",
        "where": "The operating state's Secretary of State (certificate of authority / foreign registration). Ask counsel when the facts are borderline.",
    },
    17: {
        "title": "Legal Name / DBA Consistency",
        "what": "Your exact legal name and entity type (LLC, corporation), plus any registered trade name (DBA).",
        "lender": "Small name or type differences can split your business into separate credit files that never build full history.",
        "pass": "Identical legal name and entity type across Secretary of State, IRS, bank, all bureaus and LexisNexis, with any trade name properly filed.",
        "why": "Entity-type and name mismatches are a known cause of split bureau files that never build full history.",
        "where": "Bureau update channels (with the formation document); state or county assumed-name filing.",
    },
    18: {
        "title": "Public Records / UCC",
        "what": "This checks for liens, judgments and UCC filings, the public notices lenders file when they take business assets as collateral.",
        "lender": "Existing filings affect what collateral is still available and which loans you can get next.",
        "pass": "Every open filing is in the funding file, with secured party and collateral scope understood. The point fully passes once the collateral position has been addressed with the prospective secured lender, or the strategy is limited to products that do not take a lien in business assets.",
        "why": "A legitimate UCC filing is not a defect, but broad filings limit what a new secured lender can take as collateral.",
        "where": "State Secretary of State UCC debtor search (state of formation). Only the secured party can amend or terminate a filing.",
    },
    19: {
        "title": "Duplicate Business Files",
        "what": "This checks whether a bureau has more than one file for your business.",
        "lender": "Payments can land on a file the lender never pulls, so your good history doesn't count.",
        "pass": "One file per bureau, confirmed by searches under every name variant, EIN, master and prior addresses and phone.",
        "why": "Duplicate files split payment history, so the file a lender pulls can look thinner than the business really is.",
        "where": "Experian BusinessCreditFacts / business disputes; D&B D-U-N-S Manager; Equifax Commercial Research Request.",
    },
    20: {
        "title": "Core Business Record Consistency",
        "what": "This is the overall check that every record (IRS, state, bank, bureaus, online) describes your company the same way.",
        "lender": "Mismatched records are one of the biggest reasons applications get declined without explanation. Fixing this resolves most of the audit.",
        "pass": "One legal name, one entity type, one EIN, one master address, one phone, one website, one NAICS/SIC pair and one revenue basis appearing identically on every record a lender can pull.",
        "why": "Record inconsistency is one of the largest drivers of automated declines that are never explained to the applicant.",
        "where": "Action Center and Resource Directory. Fixed order: EIN → master address → name/type → codes, phone, website → revenue/employees → re-verify → then build depth.",
    },
}

ROOT_CAUSES = [
    ("Lender-facing identity consistency", [1, 15, 17, 19, 20],
     "the records do not all describe the same company. Fixing the identity resolves most of the audit."),
    ("Verifiable business infrastructure", [6, 7, 8, 9, 14],
     "independent proof of the business (phone listing, domain email, website, Google profile) is incomplete."),
    ("Commercial bureau depth and alignment", [4, 11, 12],
     "the business credit files are thin or misaligned, so lenders have little payment history to score."),
    ("Legal standing", [2, 3, 5, 16],
     "the entity's legal standing needs attention before a lender can close."),
]

BUREAU_EXPLAIN = {
    "Experian Business": "Experian keeps a business credit file built mostly from what your suppliers, card issuers and lenders report about how you pay, plus public records and company details. Many online lenders, card issuers and suppliers check it. It is completely separate from your personal Experian file.",
    "Dun & Bradstreet": "D&B identifies your business by a D-U-N-S number and gathers payment experiences, mainly from suppliers. Banks, large vendors and government buyers often look here. You can view and update your basic company information for free in D&B's Profile Manager. A blank PAYDEX means \"not enough history yet,\" not \"bad.\"",
    "Equifax Business": "Equifax keeps a business file that draws heavily on reporting from banks and card issuers. Banks and SBA lenders often check it. It can be empty even when your other files aren't.",
    "LexisNexis": "LexisNexis is a public-records and identity database that links businesses, owners, addresses, liens and filings. Lenders use it to confirm your business is who it says it is.",
}

BUREAU_CHANNELS = {
    "Experian Business": "Identity updates: BusinessCreditFacts.com (authenticated officer). Data disputes: the Submit Data Dispute link on a live report, or BusinessDisputes@experian.com. Investigations generally complete in about 30 days.",
    "Dun & Bradstreet": "Free company-information updates and payment-experience disputes: D-U-N-S Profile Manager (dnb.com/duns/duns-manager). An officer or owner must verify.",
    "Equifax Business": "Equifax Commercial Research Request Form via commercialdisclosures@equifax.com (verify the current phone number before publishing).",
    "LexisNexis": "LexisNexis Risk Solutions business-file request (verify the current contact before publishing).",
}

SCORE_EXPLAIN = {
    "intelliscore": "Experian's main business score: how likely the business is to pay seriously late in the next year. Version 2 runs 1–100 (76+ is good); version 3 runs 300–850 (721+ is good).",
    "paydex": "D&B's 1–100 score of how promptly you pay suppliers. 80 means on time; it appears only after at least three payment experiences from two suppliers.",
    "failure": "D&B's estimate of the chance the business closes or seeks relief from creditors in the next year — class 1 is lowest risk, class 5 highest.",
    "delinquency": "D&B's estimate of the chance the business pays severely late in the next year — class 1 is best.",
    "fsr": "Experian's estimate of the chance the business fails to meet its obligations in the next year, as a 1–5 risk class (1–2 is good).",
    "dbt": "Days Beyond Terms: how many days after the due date the business pays, weighted by dollars. 0 is ideal.",
}

RESOURCE_DIRECTORY = [
    ("IRS Business & Specialty Tax Line", "01, 15", "800-829-4933 (Mon–Fri 7am–7pm local). Letter 147C to an authorized person."),
    ("IRS Form 8822-B", "01, 15", "irs.gov/form8822b — business address or responsible-party change. Only if the IRS record must change."),
    ("State Secretary of State", "02, 03, 16, 17, 18", "Business-entity search, status certificate, change of agent, annual report, assumed name, UCC debtor search. Find your state's office at nass.org."),
    ("SBA business guide", "02, 05, 16", "sba.gov — register your business; apply for licenses and permits."),
    ("U.S. Census NAICS search", "04", "census.gov/naics"),
    ("OSHA SIC Manual", "04", "osha.gov/data/sic-manual"),
    ("USPS ZIP Code Lookup", "15", "tools.usps.com — standardize the master address."),
    ("Experian BusinessCreditFacts", "04, 06, 09, 15, 17, 20", "businesscreditfacts.com — identity updates by an authenticated officer."),
    ("Experian business disputes", "11, 17, 19", "BusinessDisputes@experian.com, or the dispute link on a live report."),
    ("D&B D-U-N-S Manager", "04, 06, 09, 15, 19, 20", "dnb.com/duns/duns-manager — free view and update."),
    ("Equifax Commercial", "04, 11, 15, 19", "commercialdisclosures@equifax.com — report and Research Request Form."),
    ("LexisNexis Risk Solutions", "13, 19", "Business-file request; owner's personal disclosure at consumer.risk.lexisnexis.com."),
    ("ListYourself.net", "06", "Free national directory-assistance listing."),
    ("Google Business Profile", "14", "business.google.com; guidelines at support.google.com/business/answer/3038177."),
    ("ICANN Lookup", "07", "lookup.icann.org — domain registration data."),
    ("FTC IdentityTheft.gov", "Guarantor", "Only if an account or inquiry is genuinely not yours."),
    ("AnnualCreditReport.com", "Guarantor", "Free personal credit reports from all three bureaus."),
]

GLOSSARY = [
    ("AU (authorized user)", "A person added to someone else's credit card. The account can appear on their report, but lenders reviewing manually often discount it."),
    ("Blanket lien", "A UCC filing that covers all or most business assets, which limits what a new lender can take as collateral."),
    ("CMRA / PMB", "A commercial mail-receiving agency (a private mailbox store). Its address must carry the \"PMB\" designation and is not a physical office."),
    ("Collateral", "An asset pledged to secure a loan."),
    ("Composite score", "TLA's overall readiness score. It is issued only when the file is complete enough to describe the business accurately."),
    ("DBT (days beyond terms)", "How many days after the due date a business pays its suppliers, weighted by dollars."),
    ("DSCR", "Debt service coverage ratio: cash flow available to pay debts divided by the debt payments. Banks typically want 1.25 or more."),
    ("D-U-N-S number", "Dun & Bradstreet's nine-digit identifier for a business file."),
    ("DTI (debt-to-income)", "Monthly debt payments divided by monthly income."),
    ("EIN", "Employer Identification Number — the business's federal tax ID from the IRS."),
    ("Entity type", "The legal form of the business: LLC, corporation, partnership, etc."),
    ("FICO score", "The personal credit score most lenders use, from 300 to 850."),
    ("Hard inquiry", "A record that a lender checked your credit for an application. Many recent inquiries can lower approvals."),
    ("Intelliscore Plus", "Experian's main business credit score."),
    ("KYC", "Know Your Customer — the identity checks banks and lenders must perform."),
    ("LexisNexis", "A data company lenders use to verify business and personal identity and public records."),
    ("MCA (merchant cash advance)", "An advance repaid from daily or weekly debits from future sales. Usually far more expensive than a loan."),
    ("Master business address", "The one address, chosen by you and backed by proof, that every record should show."),
    ("NAICS / SIC", "Standard industry codes that describe what your business does."),
    ("Net-30 account", "A vendor account that lets you pay within 30 days; some report your payments to the business bureaus."),
    ("PAYDEX", "Dun & Bradstreet's 1–100 business payment score; 80 means you pay on time."),
    ("Personal guarantee (PG)", "Your promise to repay the business debt personally if the business can't."),
    ("Secretary of State (SOS)", "The state office where your business is registered."),
    ("SBFE", "Small Business Financial Exchange — a lender-only data exchange of small-business loan and card payment data."),
    ("SBA loan", "A bank loan partly guaranteed by the U.S. Small Business Administration."),
    ("Thin file", "A credit file with too little reported history to produce a reliable score."),
    ("Tradeline", "Any credit account that appears on a credit report."),
    ("UCC filing", "A public notice a lender files with the state when it takes business assets as collateral."),
    ("Use of proceeds", "Exactly what the borrowed money will be spent on."),
    ("Utilization", "Credit card balances divided by credit limits. Under 10% is excellent; over 30% starts to hurt."),
    ("W-9", "The IRS form a business gives a bank or payer to certify its tax ID."),
    ("Letter 147C", "An IRS letter confirming a business's EIN, requested by phone."),
    ("CP 575", "The IRS notice issued when an EIN is first assigned."),
    ("Source of repayment", "Where the money to repay a loan will come from — usually business cash flow."),
]

DISCLAIMER_SHORT = ("Assessment only — not a loan application, commitment, or promise of financing. "
                    "Final decisions are made by lenders.")

DISCLOSURES = [
    "The Funding Readiness Audit is a fundability and lender-preparation analysis. It is not a loan application, a commitment to lend, or a promise of financing, approval, amounts, pricing or terms. Final decisions are made by lenders and financial institutions.",
    "Tradeline Associates Inc. is not acting as a lender, CPA, accountant, bookkeeper, tax preparer, tax advisor or legal counsel. Financial statements and tax returns are reviewed as underwriting source documents only; TLA does not reconcile books, certify financial statements, provide tax advice or give legal opinions.",
    "Funding ranges, where shown, are indicative estimates based on typical lender criteria and the documents reviewed. Lenders use their own criteria and may decide differently.",
    "Scores are shown with the model, source and date they came from. Lenders may use different scores.",
    "TLA does not invent data, does not assume missing facts, and does not recommend disputing accurate information. You have the right to dispute information you believe is inaccurate or incomplete directly with the credit bureau or the company that reported it, free of charge.",
    "Business financing usually requires a personal guarantee, which makes you personally liable. Promotional (0%) rates end; plan repayment before the promotional period expires.",
    "Corrections, documents, account updates and communications with banks, bureaus and lenders remain the responsibility of the client unless separately engaged in writing.",
]

# Phrases the report must never contain (RULEBOOK §12 + r3 guardrails).
FORBIDDEN_PHRASES = [
    "remove negative", "delete accurate", "609 letter", "cpn", "credit privacy number",
    "guaranteed approval", "guaranteed funding", "we guarantee", "you will be approved",
    "inquiry removal", "inquiry-removal", "new credit identity", "pay for delete", "pay-for-delete",
    "shelf company to", "inflate your income", "sbss score estimate",
]
